version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: watcha_postgres
    restart: always
    environment:
      POSTGRES_USER: watcha_admin
      POSTGRES_PASSWORD: watcha_pw123
      POSTGRES_DB: watcha_clone_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
